"""
Django settings for colisproject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ============================================================
# Configuration par variables d'environnement
#
# Rien de sensible ni de spécifique à un serveur n'est écrit en dur
# dans ce fichier : tout vient de l'environnement. En développement,
# les valeurs sont lues depuis un fichier .env à la racine du projet
# (jamais commité) ; en production, depuis les variables définies
# dans cPanel > Setup Python App.
#
# Une vraie variable d'environnement l'emporte toujours sur le .env.
# ============================================================

def _load_dotenv(path):
    """Charge un .env minimal (KEY=valeur) sans écraser l'environnement réel."""
    if not path.exists():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        # setdefault : la variable d'environnement du serveur prime.
        os.environ.setdefault(key, value)


_load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


# ============================================================
# DEBUG
#
# Defaut volontairement a False : oublier de definir la variable sur
# le serveur ne peut donc JAMAIS allumer le mode debug en production.
# En local, DJANGO_DEBUG=True est fourni par le fichier .env.
# ============================================================

DEBUG = _env_bool('DJANGO_DEBUG', default=False)


# ============================================================
# SECRET_KEY
#
# Sert aussi de SIGNING_KEY aux jetons JWT (voir SIMPLE_JWT plus bas) :
# quiconque la connait peut forger un jeton valide. Elle ne doit donc
# jamais se trouver dans le depot git.
#
# En production, l'absence de la variable arrete le demarrage plutot
# que de retomber silencieusement sur une cle connue.
#
# Generer une cle :
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
# ============================================================

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-key-jamais-utilisee-en-production'
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY n'est pas definie. En production, la renseigner "
            "dans les variables d'environnement de l'application "
            "(cPanel > Setup Python App > Environment variables)."
        )


# ============================================================
# ALLOWED_HOSTS : liste blanche de l'en-tete Host de la requete.
#
# Rien a voir avec CORS/CSRF_TRUSTED_ORIGINS : ceux-ci filtrent
# l'en-tete Origin (navigateurs uniquement) et ne remplacent pas
# cette liste. Un client Android passe ici avec le domaine/IP
# de sa baseUrl -> il doit figurer dans la liste.
#
# Les domaines de production sont listes INCONDITIONNELLEMENT.
# Les placer dans un « else: » d'un test sur DEBUG est un piege :
# si DEBUG se retrouve a True sur le serveur, le domaine disparait
# de la liste et Django renvoie 400 sur absolument toutes les
# requetes - site entier hors service, pas seulement l'API.
#
# (les ports ne se mettent pas dans ALLOWED_HOSTS)
# ============================================================

PRODUCTION_HOSTS = [
    'lukogoexpresscompany.com',
    'www.lukogoexpresscompany.com',
]

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '[::1]',
] + PRODUCTION_HOSTS

if DEBUG:
    ALLOWED_HOSTS += [
        '10.0.2.2',    # emulateur Android (AVD) vers la machine hote
        '10.0.3.2',    # emulateur Genymotion
        'testserver',  # client de test Django
    ]

# Hotes supplementaires via variable d'environnement. Pour tester
# l'app sur un TELEPHONE PHYSIQUE en dev, y mettre l'IP LAN du PC :
#   DJANGO_ALLOWED_HOSTS=192.168.1.42
ALLOWED_HOSTS += _env_list('DJANGO_ALLOWED_HOSTS')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'main',
    'django_bootstrap5',

    # API
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'colisproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'colisproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
MEDIA_URL = '/media/'
LOGIN_URL = '/login/'
MEDIA_ROOT = BASE_DIR/ 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# API — Django REST Framework
# Consommée par l'application Android (Lukogo Express).
# ============================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Gardée pour pouvoir tester l'API depuis le navigateur en étant connecté.
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'main.api.pagination.StandardPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'main.api.exceptions.api_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'register': '5/hour',
    },
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'TOKEN_OBTAIN_SERIALIZER': 'main.api.serializers.LukogoTokenObtainPairSerializer',
}

# ==========================================
# CORS
#
# Android/Retrofit n'est PAS soumis au CORS (c'est une regle de
# navigateur). Ces reglages servent uniquement a pouvoir tester
# l'API depuis une page web ou un client Swagger.
# ==========================================

# Toutes origines autorisees en developpement uniquement.
CORS_ALLOW_ALL_ORIGINS = DEBUG

# Origines de production listees inconditionnellement, pour la meme
# raison que ALLOWED_HOSTS plus haut : elles ne doivent pas dependre
# de la valeur de DEBUG.
CORS_ALLOWED_ORIGINS = ['https://' + host for host in PRODUCTION_HOSTS]

if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ]

CORS_ALLOW_CREDENTIALS = True
# Appliquer CORS uniquement aux URLs de l'API.
CORS_URLS_REGEX = r'^/api/.*$'


# ==========================================
# CSRF
# ==========================================

CSRF_TRUSTED_ORIGINS = ['https://' + host for host in PRODUCTION_HOSTS]

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
    ]

# Origines supplementaires via variable d'environnement, ex :
#   DJANGO_CSRF_TRUSTED_ORIGINS=https://api.mondomaine.bi
CSRF_TRUSTED_ORIGINS += _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')
