# Generated by Django 4.2.25 on 2025-10-19 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('vehicle_plate', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('departure_point', models.CharField(max_length=100)),
                ('arrival_point', models.CharField(max_length=100)),
                ('intermediate_stops', models.TextField(blank=True, null=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_manifests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('client_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('measure', models.CharField(choices=[('kilo', 'Kilo'), ('little', 'Littre'), ('can', 'Bidon'), ('piece', 'Pièce')], default='kilos', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Attente'), ('in_transit', 'En transit'), ('delivered', 'Délivré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_created', to=settings.AUTH_USER_MODEL)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='main.manifesttable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='main.packagetable')),
            ],
        ),
    ]
