# Generated by Django 4.2.25 on 2025-10-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesttable',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
