# Generated by Django 4.2.25 on 2025-10-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_manifesttable_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurePriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(choices=[('kilo', 'Kilo'), ('little', 'Littre'), ('can', 'Bidon'), ('piece', 'Pièce')], default='kilo', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='packagetable',
            name='measure',
            field=models.CharField(choices=[('kilo', 'Kilo'), ('little', 'Littre'), ('can', 'Bidon'), ('piece', 'Pièce')], default='kilo', max_length=20),
        ),
    ]
