# Generated by Django 4.2.25 on 2025-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_measurepricetable_alter_packagetable_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetable',
            name='receiver_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
