# Generated by Django 4.2.25 on 2025-10-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_packagetable_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetable',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
