# Generated by Django 4.2.25 on 2025-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_packagetable_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesttable',
            name='intermediate_stops',
            field=models.TextField(blank=True, null=True, verbose_name='Intermediate stops'),
        ),
    ]
