# Generated by Django 4.2.25 on 2025-11-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_manifesttable_intermediate_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesttable',
            name='intermediate_stops',
            field=models.TextField(blank=True, default='Non', null=True),
        ),
    ]
