# Generated by Django 4.2.25 on 2025-11-15 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_manifesttable_intermediate_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetable',
            name='taken_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
