# Generated by Django 4.2.25 on 2026-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_packagetable_taken_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetable',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
