# Generated by Django 4.2.25 on 2026-01-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_packagetable_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetable',
            name='weight',
            field=models.FloatField(),
        ),
    ]
